<?php

/**
 * @file
 * Umd_terp_base module file.
 */

/**
 * Implements hook_preprocess_paragraph().
 *
 * @param $variables
 *   Adds some them settings/info to paragraphs.
 */
function umd_terp_base_preprocess_paragraph(&$variables) {
  // Need some theme settings for asset path/etc.
  if (function_exists('_umd_terp_extend_theme_variables')) {
    _umd_terp_extend_theme_variables($variables);
  }
}

/**
 * Implements hook_toolbar().
 *
 * Adds admin edit links/tabs in toolbar, so we don't need to have directly on the page.
 */
function umd_terp_base_toolbar() {
  return \Drupal::service('umd_terp_base.edit_button')
    ->addEdit();
}
