<?php

/**
 * @file
 * Ut_card module install file.
 */

/**
 * Reset all paragraph fields to match standard config.
 */
function ut_card_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'ut_card');
}

/**
 * Update to add columns to card groups.
 */
function ut_card_update_8002() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'ut_card');
}

/**
 * Add column-specific image styles for Card Groups.
 */
function ut_card_update_8003() {
  \Drupal::service('config.installer')
    ->installDefaultConfig('module', 'ut_card');
}